export default {
    DISCORD_OPEN_EVENT: 'Discord:Opened',
    DISCORD_LOGIN_EVENT: 'Discord:Login',
    TO_CLIENT_SET_INTO_VEHICLE: 'to:Client:SetIntoVehicle',
    TO_CLIENT_INIT_WEBVIEWS: 'init:Webviews',
    TO_CLIENT_OPEN_VEHICLE_SELECT: 'to:Client:OpenVehicleSelection',
    TO_CLIENT_UPDATE_TIMER: 'to:Client:UpdateTimer',
    TO_CLIENT_CANISTER: 'to:Client:UpdateCanister',
    TO_CLIENT_GOAL: 'to:Client:Goal',
    TO_SERVER_SELECT_VEHICLE: 'to:Server:SelectVehicle',
    TO_SERVER_WEBVIEWS_INITIALIZED: 'to:Server:WebviewsInitialized',
    META_SPAWN_PROTECTION: 'Meta:SpawnProtection',
    META_SCORE: 'Meta:Score',
    META_READY: 'Meta:Ready',
    META_NAME: 'Meta:Name',
    META_POS: 'Meta:Pos',
    META_CANISTER: 'Meta:Canister',
};
